language: java
jdk: 
- openjdk11

addons:
 sonarcloud:
  organization: salvatorefoderaro
  token: 44974beda955c79075c451f44efe48a3095df401
script: 
- mvn verify -DfailIfNoTests=false sonar:sonar -Dsonar.projectKey=salvatorefoderaro_avro 