language: java
jdk: 
- openjdk11

addons:
 sonarcloud:
  organization: salvatorefoderaro
  token: f9a39f43a04ed7658b1aa06792313008bfd85b5e
script:
- mvn verify -DfailIfNoTests=false sonar:sonar -Dsonar.projectKey=salvatorefoderaro_bookkeeper 